options:
  port:
    type: int
    default: 9099
    description: "cAdvisor listening port."
  install_source:
    type: string
    default: ""
    description: "A short description of the configuration option"
  install_keys:
    type: string
    default: ""
    description: "A short description of the configuration option"
  install_file:
    type: string
    default: ""
    description: |
      Location where cAdvisor .deb package can be found. If isntall_sources
      and install_keys opetinos are ignored. Example: |
        install_file: htt://my.company.com/packages/cadvisor/cadvisor_0.25_amd64.deb
  http_proxy:
    default: ""
    type: string
    description: |
      Proxy URL to use for install_file
  standalone:
    type: boolean
    default: true
    description: |
      This is only for Trusty distro without docker and running as standalone. Once enabled,
      it will connect to default docker endpoint (unix:///var/run/docker.sock).
