options:
  port:
    type: int
    default: 8080
    description: "cAdvisor listening port."
  install_source:
    type: string
    default: ""
    description: "A short description of the configuration option"
  install_keys:
    type: string
    default: ""
    description: "A short description of the configuration option"
  install_file:
    type: string
    default: "http://archive.ubuntu.com/extra/cadvisor/cadvisor_0.28.3.6+5a2e3d06pannet_amd64.deb"
    description: |
      Location where cAdvisor .deb package can be found. If isntall_sources
      and install_keys opetinos are ignored. Example: |
        install_file: htt://my.company.com/packages/cadvisor/cadvisor_0.25_amd64.deb
  http_proxy:
    default: ""
    type: string
    description: |
      Proxy URL to use for install_file
  standalone:
    type: boolean
    default: true
    description: |
      This is only for Trusty distro without docker and running as standalone. Once enabled,
      it will connect to default docker endpoint (unix:///var/run/docker.sock).
  storage:
    type: boolean
    default: false
    description: |
      Storage driver to use. Data is always cached shortly in memory, this controls
      where data is pushed besides the local cache. Default is storage_driver_host=localhost:8086
